version: '3'

services:
  jmri:
    image: jsa1987/jmri-docker:testing
    container_name: jmri
    restart: unless-stopped
    ports:
      # Web interface
      - "12080:12080"
      # Default LocoNet over TCP port
      - "1234:1234"
      # WiThrottle server
      - "12090:12090"
      # JMRI JSON server
      - "2056:2056"
      # VNC server
      - "5901:5901"
      # noVNC web interface
      - "6901:6901"
    volumes:
      # Mount JMRI configuration directory
      - ./jmri_config:/root/.jmri
    environment:
      - TZ=UTC 